aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.kubeflow.org/aggregate-to-kubeflow-kuberay-admin: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeflow-kuberay-admin
  labels:
    app: kuberay-operator
    app.kubernetes.io/name: kuberay-operator
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-admin: "true"
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeflow-kuberay-editor
  labels:
    app: kuberay-operator
    app.kubernetes.io/name: kuberay-operator
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: "true"
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-kuberay-admin: "true"
rules:
- apiGroups:
  - ray.io
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  resources: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeflow-kuberay-view
  labels:
    app: kuberay-operator
    app.kubernetes.io/name: kuberay-operator
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-view: "true"
rules:
- apiGroups:
  - ray.io
  verbs: ["get", "list", "watch"]
  resources: ["*"]
---
